# Task 2: Linear Algebra Foundations for Quantum Computing

**Starter Notebook**

## Learning Objectives

- Represent quantum states as column vectors
- Implement quantum gates as unitary matrices
- Apply gate operations using matrix multiplication
- Calculate inner products and tensor products
- Analyse quantum operators through eigenvalue decomposition

## Prerequisites

- Basic Python programming
- Fundamental linear algebra concepts

## Estimated Time: 30-45 minutes

## Instructions

Complete each exercise by writing code in the provided cells. Use the hints and background information to guide you. Compare your results with the expected outputs.

**Tip:** If you get stuck, refer to the solution notebook or the task README.md for additional guidance.

In [ ]:
# Google Colab Setup - Run this cell first if using Colab
import sys
if 'google.colab' in sys.modules:
    print("📦 Installing dependencies for Google Colab...")
    !pip install -q numpy>=1.24.0 matplotlib
    print("✓ Dependencies installed successfully!")
    print("You can now run the rest of the notebook.\n")
else:
    print("✓ Running in local environment")

## Setup and Imports

In [ ]:
# Import NumPy for numerical linear algebra operations
import numpy as np

# Set print options for better readability
np.set_printoptions(precision=4, suppress=True)

print("NumPy version:", np.__version__)
print("Setup complete! ✓")

---

## Exercise 1: Create a Quantum State as a Column Vector

### Background

In quantum mechanics, a quantum state is represented as a column vector in a complex vector space. For a single qubit, we use a 2D column vector:

$$|\psi\rangle = \begin{pmatrix} \alpha \\ \beta \end{pmatrix}$$

where $|\alpha|^2 + |\beta|^2 = 1$ (normalisation condition).

The computational basis states are:
- $|0\rangle = \begin{pmatrix} 1 \\ 0 \end{pmatrix}$
- $|1\rangle = \begin{pmatrix} 0 \\ 1 \end{pmatrix}$

### Your Task

Create the quantum state $|0\rangle$ as a NumPy column vector.

**Hints:**
- Use `np.array([[a], [b]])` to create a column vector (note the double brackets)
- For $|0\rangle$, the first component is 1 and the second is 0
- Verify the shape is `(2, 1)` not `(2,)`

In [ ]:
# YOUR CODE HERE: Create quantum state |0⟩ as a column vector
# Hint: quantum_state = np.array([[?, ?]])


# Verification code (run after implementing)
print("Quantum state |0⟩:")
print(quantum_state)
print(f"\nShape: {quantum_state.shape}")

# Check normalisation
norm = np.linalg.norm(quantum_state)
print(f"\nNorm: {norm:.4f}")
if np.isclose(norm, 1.0):
    print("✓ State is properly normalised")
else:
    print("✗ Check your implementation - state should be normalised")

**Expected Output:**
```
Quantum state |0⟩:
[[1]
 [0]]
Shape: (2, 1)
Norm: 1.0000
✓ State is properly normalised
```

---

## Exercise 2: Create the Pauli-X Gate Matrix

### Background

The Pauli-X gate is the quantum equivalent of a classical NOT gate. It flips the computational basis states:

$$X = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$$

Properties:
- $X|0\rangle = |1\rangle$
- $X|1\rangle = |0\rangle$
- $X^2 = I$ (applying X twice returns to original state)

### Your Task

Create the Pauli-X gate as a 2×2 NumPy matrix.

**Hints:**
- Use `np.array([[row1], [row2]])` for a 2×2 matrix
- First row: [0, 1]
- Second row: [1, 0]

In [ ]:
# YOUR CODE HERE: Create Pauli-X gate matrix
# Hint: pauli_x_gate = np.array([[?, ?], [?, ?]])


# Verification code
print("Pauli-X (NOT) Gate:")
print(pauli_x_gate)
print(f"\nShape: {pauli_x_gate.shape}")

# Check if unitary
x_dagger = pauli_x_gate.conj().T
product = np.dot(x_dagger, pauli_x_gate)
if np.allclose(product, np.eye(2)):
    print("✓ Gate is unitary (X†X = I)")
else:
    print("✗ Check your implementation - gate should be unitary")

**Expected Output:**
```
Pauli-X (NOT) Gate:
[[0 1]
 [1 0]]
Shape: (2, 2)
✓ Gate is unitary (X†X = I)
```

---

## Exercise 3: Apply the Pauli-X Gate

### Background

To apply a quantum gate to a state, we perform matrix-vector multiplication:

$$|\psi'\rangle = U|\psi\rangle$$

For the Pauli-X gate:

$$X|0\rangle = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix} \begin{pmatrix} 1 \\ 0 \end{pmatrix} = \begin{pmatrix} 0 \\ 1 \end{pmatrix} = |1\rangle$$

### Your Task

Apply the Pauli-X gate to the quantum state $|0\rangle$ using matrix multiplication.

**Hints:**
- Use `np.dot(matrix, vector)` for matrix-vector multiplication
- The result should be $|1\rangle = \begin{pmatrix} 0 \\ 1 \end{pmatrix}$

In [ ]:
# YOUR CODE HERE: Apply Pauli-X gate to quantum state
# Hint: transformed_state = np.dot(?, ?)


# Verification code
print("Original state |0⟩:", quantum_state.flatten())
print("After applying X gate:", transformed_state.flatten())

expected_state_1 = np.array([[0], [1]])
if np.allclose(transformed_state, expected_state_1):
    print("\n✓ Correctly flipped |0⟩ to |1⟩")
else:
    print("\n✗ Check your implementation")

**Expected Output:**
```
Original state |0⟩: [1 0]
After applying X gate: [0 1]
✓ Correctly flipped |0⟩ to |1⟩
```

---

## Exercise 4: Create the Hadamard Gate

### Background

The Hadamard gate creates quantum superposition:

$$H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix}$$

Properties:
- $H|0\rangle = \frac{1}{\sqrt{2}}(|0\rangle + |1\rangle) = |+\rangle$
- $H|1\rangle = \frac{1}{\sqrt{2}}(|0\rangle - |1\rangle) = |-\rangle$

### Your Task

Create the Hadamard gate matrix.

**Hints:**
- Start with the unnormalised matrix `[[1, 1], [1, -1]]`
- Divide by `np.sqrt(2)` to normalise
- The factor $\frac{1}{\sqrt{2}} \approx 0.7071$

In [ ]:
# YOUR CODE HERE: Create Hadamard gate matrix
# Hint: hadamard_gate = np.array([[?, ?], [?, ?]]) / np.sqrt(2)


# Verification code
print("Hadamard Gate:")
print(hadamard_gate)

# Check if unitary
h_dagger = hadamard_gate.conj().T
product = np.dot(h_dagger, hadamard_gate)
if np.allclose(product, np.eye(2)):
    print("✓ Gate is unitary")

# Check if self-inverse
h_squared = np.dot(hadamard_gate, hadamard_gate)
if np.allclose(h_squared, np.eye(2)):
    print("✓ H² = I (self-inverse property)")

**Expected Output:**
```
Hadamard Gate:
[[ 0.7071  0.7071]
 [ 0.7071 -0.7071]]
✓ Gate is unitary
✓ H² = I (self-inverse property)
```

---

## Exercise 5: Apply the Hadamard Gate

### Background

Applying the Hadamard gate to $|0\rangle$ creates an equal superposition:

$$H|0\rangle = \frac{1}{\sqrt{2}}(|0\rangle + |1\rangle) = |+\rangle$$

This state has equal probability (50%) of measuring 0 or 1.

### Your Task

Apply the Hadamard gate to $|0\rangle$ and calculate the measurement probabilities.

**Hints:**
- Use `np.dot()` for matrix-vector multiplication
- Probability of measuring $|0\rangle$: $P(0) = |\alpha|^2$ where $\alpha$ is the first component
- Probability of measuring $|1\rangle$: $P(1) = |\beta|^2$ where $\beta$ is the second component

In [ ]:
# YOUR CODE HERE: Apply Hadamard gate and calculate probabilities
# Step 1: Apply Hadamard to quantum_state
# transformed_state_hadamard = ?

# Step 2: Calculate probabilities
# prob_0 = ?
# prob_1 = ?


# Verification code
print("After applying Hadamard gate:")
print(transformed_state_hadamard.flatten())
print("\nMeasurement probabilities:")
print(f"P(0) = {prob_0:.4f}")
print(f"P(1) = {prob_1:.4f}")

if np.isclose(prob_0, 0.5) and np.isclose(prob_1, 0.5):
    print("\n✓ Equal superposition created (50%/50%)")

**Expected Output:**
```
After applying Hadamard gate:
[0.7071 0.7071]
Measurement probabilities:
P(0) = 0.5000
P(1) = 0.5000
✓ Equal superposition created (50%/50%)
```

---

## Exercise 6: Calculate Inner Product

### Background

The inner product between two quantum states $|\psi\rangle$ and $|\phi\rangle$ is:

$$\langle\psi|\phi\rangle = \sum_i \psi_i^* \phi_i$$

**Physical meaning:**
- $|\langle\psi|\phi\rangle|^2$ gives the probability of measuring $|\psi\rangle$ when in state $|\phi\rangle$
- Orthogonal states have inner product zero: $\langle 0|1\rangle = 0$

### Your Task

Calculate the inner product between $|0\rangle$ and $|1\rangle$.

**Hints:**
- First create $|1\rangle$ as `np.array([[0], [1]])`
- Use `np.vdot(vector1.flatten(), vector2.flatten())` for inner product
- The result should be 0 (orthogonal states)

In [ ]:
# YOUR CODE HERE: Calculate inner product
# Step 1: Create |1⟩ state
# quantum_state_2 = ?

# Step 2: Calculate inner product using np.vdot
# inner_product = ?


# Verification code
print("State 1 (|0⟩):", quantum_state.flatten())
print("State 2 (|1⟩):", quantum_state_2.flatten())
print(f"\nInner product ⟨0|1⟩ = {inner_product}")

if np.isclose(inner_product, 0):
    print("\n✓ States are orthogonal (inner product = 0)")

**Expected Output:**
```
State 1 (|0⟩): [1 0]
State 2 (|1⟩): [0 1]
Inner product ⟨0|1⟩ = 0
✓ States are orthogonal (inner product = 0)
```

---

## Exercise 7: Create Gate Sequence

### Background

Multiple gates can be applied sequentially. For gates applied in order $U_1$, then $U_2$, then $U_3$:

$$|\psi'\rangle = U_3(U_2(U_1|\psi\rangle)) = (U_3 U_2 U_1)|\psi\rangle$$

Note the reverse order in the matrix product!

### Your Task

Apply the gate sequence X → H to $|0\rangle$ (X first, then H).

**Hints:**
- First apply X to $|0\rangle$ to get $|1\rangle$
- Then apply H to the result
- Use nested `np.dot()` calls: `np.dot(H, np.dot(X, state))`
- The final result should be the $|-\rangle$ state

In [ ]:
# YOUR CODE HERE: Apply gate sequence X → H
# circuit_result = ?


# Verification code
print("Final result after X → H:")
print(circuit_result.flatten())

# This should be the |-⟩ state
minus_state = np.array([[1], [-1]]) / np.sqrt(2)
if np.allclose(circuit_result, minus_state):
    print("\n✓ Successfully created |-⟩ state = (|0⟩ - |1⟩)/√2")

**Expected Output:**
```
Final result after X → H:
[ 0.7071 -0.7071]
✓ Successfully created |-⟩ state = (|0⟩ - |1⟩)/√2
```

---

## Exercise 8: Calculate Tensor Product

### Background

The **tensor product** (Kronecker product) combines quantum states of multiple qubits:

$$|0\rangle \otimes |1\rangle = |01\rangle = \begin{pmatrix} 0 \\ 1 \\ 0 \\ 0 \end{pmatrix}$$

This creates a 4-dimensional vector for a 2-qubit system.

### Your Task

Calculate the tensor product of $|0\rangle$ and $|1\rangle$.

**Hints:**
- Use `np.kron(state1, state2)` for tensor product
- The result should be shape `(4, 1)`
- For $|01\rangle$, only the second component is 1

In [ ]:
# YOUR CODE HERE: Calculate tensor product
# tensor_product = ?


# Verification code
print("Tensor product |0⟩ ⊗ |1⟩ = |01⟩:")
print(tensor_product.flatten())
print(f"\nShape: {tensor_product.shape}")

expected_01 = np.array([[0], [1], [0], [0]])
if np.allclose(tensor_product, expected_01):
    print("\n✓ Correctly created two-qubit state |01⟩")

**Expected Output:**
```
Tensor product |0⟩ ⊗ |1⟩ = |01⟩:
[0 1 0 0]
Shape: (4, 1)
✓ Correctly created two-qubit state |01⟩
```

---

## Exercise 9: Create Identity Matrix

### Background

The **identity gate** is the "do nothing" operation:

$$I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$$

Properties:
- $I|\psi\rangle = |\psi\rangle$ for any state
- Useful in multi-qubit gates (e.g., $I \otimes X$)

### Your Task

Create the 2×2 identity matrix and verify it leaves states unchanged.

**Hints:**
- Use `np.eye(n)` to create an n×n identity matrix
- Verify: $I|0\rangle = |0\rangle$

In [ ]:
# YOUR CODE HERE: Create identity matrix
# identity_matrix = ?


# Verification code
print("Identity matrix (2×2):")
print(identity_matrix)

result_0 = np.dot(identity_matrix, quantum_state)
if np.allclose(result_0, quantum_state):
    print("\n✓ Identity gate correctly preserves states")

**Expected Output:**
```
Identity matrix (2×2):
[[1. 0.]
 [0. 1.]]
✓ Identity gate correctly preserves states
```

---

## Exercise 10: Calculate Eigenvalues and Eigenvectors

### Background

Eigenvalue decomposition is central to quantum mechanics:

$$A|\lambda\rangle = \lambda|\lambda\rangle$$

**Physical interpretation:**
- Eigenvalues = possible measurement outcomes
- Eigenvectors = states that yield definite results

### Your Task

Find eigenvalues and eigenvectors of $A = \begin{pmatrix} 3 & 1 \\ 1 & 2 \end{pmatrix}$.

**Hints:**
- Define the matrix as `np.array([[3, 1], [1, 2]])`
- Use `np.linalg.eig(matrix)` which returns `(eigenvalues, eigenvectors)`
- Verify: $A|\lambda\rangle = \lambda|\lambda\rangle$ for each eigenpair

In [ ]:
# YOUR CODE HERE: Calculate eigenvalues and eigenvectors
# Step 1: Define the matrix
# matrix = ?

# Step 2: Calculate eigenvalues and eigenvectors
# eigenvalues, eigenvectors = ?


# Verification code
print("Matrix A:")
print(matrix)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors (as columns):")
print(eigenvectors)

# Verify eigenvalue equation for first eigenpair
eigenvector_0 = eigenvectors[:, 0]
eigenvalue_0 = eigenvalues[0]
left_side = matrix @ eigenvector_0
right_side = eigenvalue_0 * eigenvector_0

if np.allclose(left_side, right_side):
    print("\n✓ Eigenvalue equation verified: A|λ⟩ = λ|λ⟩")

**Expected Output:**
```
Matrix A:
[[3 1]
 [1 2]]
Eigenvalues:
[3.618...  1.381...]
Eigenvectors (as columns):
[[ 0.8507... -0.5257...]
 [ 0.5257...  0.8507...]]
✓ Eigenvalue equation verified: A|λ⟩ = λ|λ⟩
```

---

## Summary

Congratulations! You've completed Task 2 and learned:

### ✅ Core Concepts

1. **Quantum states as vectors** - Column vectors in Hilbert space
2. **Quantum gates as matrices** - Unitary transformations
3. **Gate application** - Matrix-vector multiplication
4. **Inner products** - State overlap and probabilities
5. **Tensor products** - Multi-qubit systems
6. **Eigenvalue decomposition** - Measurement theory

### 🎯 Next Steps

1. Compare your solutions with `task_02_solution.ipynb`
2. Run the tests: `pytest tests/test_task_02.py`
3. Proceed to **Task 1** to use these concepts with Qiskit

### 📚 Additional Practice

Try these extensions:
- Implement other Pauli gates (Y, Z)
- Create three-qubit states
- Verify all single-qubit gates are unitary
- Calculate expectation values

**Well done!** You now have a solid foundation in quantum computing mathematics. 🎉